AWSTemplateFormatVersion: '2010-09-09'
Description: 'Existing VPC deployment: single-node Tableau Server running on Windows or Amazon Linux 2. (qs-1puphiil4)'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'AWS environment and machine configuration'
        Parameters:
          - VPCID
          - PrivateSubnet1ID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - Route53HostedZone
          - Route53DomainName
          - TableauServerSubDomainName
          - InstanceType
          - OS
          - KeyPairName
          - SourceCIDR
          - TableauS3BucketName
      - Label:
          default: Secrets
        Parameters:
          - TableauServerAdminUser
          - TableauServerAdminPassword
          - TsmUsername
          - TsmPassword
          - LicenseKey
      - Label:
          default: Registration
        Parameters:
          - AcceptEULA
          - RegFirstName
          - RegLastName
          - RegEmail
          - RegCompany
          - RegTitle
          - RegDepartment
          - RegIndustry
          - RegPhone
          - RegCity
          - RegState
          - RegZip
          - RegCountry
          - RegCompanyEmployees
          - RegOptIn
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      VPCID:
        default: VPC ID

      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      Route53HostedZone:
        default: Hosted Zone
      Route53DomainName:
        default: Domain name for your hosted zone
      TableauServerSubDomainName:
        default: Tableau Server subdomain
      TableauS3BucketName:
        default: Name of S3 bucket for Tableau Server files
      InstanceType:
        default: EC2 instance type for Tableau Server
      OS:
        default: Operating System for Tableau Server
      KeyPairName:
        default: Key Pair for EC2
      SourceCIDR:
        default: CIDR block for ingress rules
      TableauServerAdminPassword:
        default: Tableau Server administrator password
      TableauServerAdminUser:
        default: Tableau Server administrator username
      TsmUsername:
        default: Tableau Services Manager (TSM) administrator username
      TsmPassword:
        default: Tableau Services Manager (TSM) administrator password
      LicenseKey:
        default: Tableau Activation Key
      AcceptEULA:
        default: Accept Tableau End User License Agreement
      RegCity:
        default: City
      RegCompany:
        default: Company
      RegCountry:
        default: Country
      RegDepartment:
        default: Department
      RegEmail:
        default: Email Address
      RegFirstName:
        default: First Name
      RegIndustry:
        default: Industry
      RegLastName:
        default: Last Name
      RegPhone:
        default: Phone
      RegState:
        default: State
      RegTitle:
        default: Title
      RegZip:
        default: Zip/Postal Code
      RegCompanyEmployees:
        default: 5
      RegOptIn:
        default: true

Parameters:
  RegIndustry:
    Description: Industry for registration
    Type: String
    Default: Technology

  TableauServerAdminPassword:
    Description: Admin password for Tableau Server
    Type: String
    NoEcho: true

  VPCID:
    Description: VPC ID for deployment
    Type: AWS::EC2::VPC::Id
    Default: vpc-080afb2ebc3ae29c2

  TsmUsername:
    Description: TSM Administrator username
    Type: String
    Default: tableauadmin2024

  QSS3KeyPrefix:
    Description: S3 Key Prefix
    Type: String
    Default: cfn-ps-tableau-server/

  RegLastName:
    Description: Last name of the user
    Type: String
    Default: Tableau

  RegPhone:
    Description: Contact phone number
    Type: String
    Default: 7207710071

  RegFirstName:
    Description: First name of the user
    Type: String
    Default: Jim

  RegTitle:
    Description: Job title of the user
    Type: String
    Default: Owner

  RegDepartment:
    Description: Department of the user
    Type: String
    Default: Infra

  RegCompany:
    Description: Company name
    Type: String
    Default: IBM

  InstanceType:
    Description: Instance type for Tableau Server
    Type: String
    Default: m5.8xlarge

  RegCity:
    Description: City of the user
    Type: String
    Default: Denver

  TableauS3BucketName:
    Description: Name of the S3 bucket for Tableau Server files
    Type: String
    Default: tableau-demo-bmf

  RegCompanyEmployees:
    Description: Number of employees in the company
    Type: String
    Default: 1

  KeyPairName:
    Description: Name of the EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    Default: defaultvpc-ec2

  QSS3BucketName:
    Description: S3 bucket for Quick Start assets
    Type: String
    Default: aws-ia

  RegZip:
    Description: ZIP/Postal code
    Type: String
    Default: 80229

  RegOptIn:
    Description: Opt-in for marketing communications
    Type: String
    Default: ''

  OS:
    Description: Operating system for Tableau Server
    Type: String
    AllowedValues:
      - Linux
      - Windows
    Default: Linux

  AcceptEULA:
    Type: String
    AllowedPattern: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'

  SourceCIDR:
    Description: CIDR block for accessing Tableau Server
    Type: String
    Default: 0.0.0.0/0

  TsmPassword:
    Description: TSM Administrator password
    Type: String
    NoEcho: true

  PrivateSubnet1ID:
    Description: Private subnet 1 ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0431940404fc0dee6

  RegCountry:
    Description: Country of the user
    Type: String
    Default: United States

  Route53HostedZone:
    Description: Hosted Zone from Route53
    Type: AWS::Route53::HostedZone::Id
    Default: Z0322061AZI6Q2VHWYLH

  RegEmail:
    Description: Email address of the user
    Type: String
    Default: jcporter@us.ibm.com

  Route53DomainName:
    Description: Domain name for the Route53 Hosted Zone
    Type: String
    Default: demo-tableau.com

  PublicSubnet1ID:
    Description: Public subnet 1 ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-092f4c86e7184cbe1

  PublicSubnet2ID:
    Description: Public subnet 2 ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-02a923916a63e6a02

  QSS3BucketRegion:
    Description: AWS Region of the Quick Start S3 bucket
    Type: String
    Default: us-east-1

  TableauServerAdminUser:
    Description: Tableau Server Administrator username
    Type: String
    Default: tableauadmin2024

  RegState:
    Description: State of the user
    Type: String
    Default: CO

  TableauServerSubDomainName:
    Description: Subdomain name for Tableau Server
    Type: String
    Default: tableau

  LicenseKey:
    Description: License Key for Tableau Server (leave blank for trial)
    Type: String
    Default: ''


Conditions:
  InfaOnWindows: !Equals
    - !Ref 'OS'
    - Windows
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-ia']

Resources:
  Infrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/tableau-server-infrastructure.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !Ref VPCID
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        Route53HostedZone: !Ref 'Route53HostedZone'
        Route53DomainName: !Ref 'Route53DomainName'
        TableauS3BucketName: !Ref 'TableauS3BucketName'
        SourceCIDR: !Ref 'SourceCIDR'
        TableauServerSubdomain: !Ref TableauServerSubDomainName
        TsmSubdomain: !Sub '${TableauServerSubDomainName}-tsm'
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'

  TableauServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/tableau-server-${TableauOS}.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            TableauOS: !If [InfaOnWindows, 'windows', 'linux']
      Parameters:
        AcceptEULA: !Ref 'AcceptEULA'
        InstanceType: !Ref 'InstanceType'
        KeyPairName: !Ref 'KeyPairName'
        S3BucketName: !GetAtt Infrastructure.Outputs.TableauS3Bucket
        TableauServerHostname:
          Fn::Sub:
            - '${prefix}.${Route53DomainName}'
            - prefix: !Ref TableauServerSubDomainName
        SecurityGroup: !GetAtt Infrastructure.Outputs.SecurityGroup
        IamInstanceProfile: !GetAtt Infrastructure.Outputs.IamInstanceProfile
        TableauIAMRole: !GetAtt Infrastructure.Outputs.TableauIAMRole
        PublicSubnetId: !Ref PrivateSubnet1ID
        TableauServerTargetGroupArn: !GetAtt Infrastructure.Outputs.TableauServerTargetGroupArn
        TsmTargetGroupArn: !GetAtt Infrastructure.Outputs.TsmTargetGroupArn
        TableauServerAdminPassword: !Ref 'TableauServerAdminPassword'
        TableauServerAdminUser: !Ref 'TableauServerAdminUser'
        LicenseKey: !Ref 'LicenseKey'
        TsmUsername: !Ref 'TsmUsername'
        TsmPassword: !Ref 'TsmPassword'
        RegCity: !Ref 'RegCity'
        RegCompany: !Ref 'RegCompany'
        RegCountry: !Ref 'RegCountry'
        RegDepartment: !Ref 'RegDepartment'
        RegEmail: !Ref 'RegEmail'
        RegFirstName: !Ref 'RegFirstName'
        RegIndustry: !Ref 'RegIndustry'
        RegLastName: !Ref 'RegLastName'
        RegPhone: !Ref 'RegPhone'
        RegState: !Ref 'RegState'
        RegTitle: !Ref 'RegTitle'
        RegZip: !Ref 'RegZip'
        RegCompanyEmployees: !Ref 'RegCompanyEmployees'
        RegOptIn: !Ref 'RegOptIn'
        TableauServerLogGroup: !GetAtt Infrastructure.Outputs.TableauServerLogGroup
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'

Outputs:
  TableauServerUrl:
    Description: URL of your Tableau Server
    Value:
      Fn::Sub:
        - "${p1}.${Route53DomainName}"
        - p1: !Ref TableauServerSubDomainName
  TableauServerTsmUrl:
    Description: Tableau Server TSM URL (Load Balancer)
    Value:
      Fn::Sub:
        - "${p1}-tsm.${Route53DomainName}"
        - p1: !Ref TableauServerSubDomainName
  SecurityGroup:
    Description: Security Group ARN
    Value: !GetAtt Infrastructure.Outputs.SecurityGroup
  TableauServerTargetGroupArn:
    Description: Tableau Server ALB TG
    Value: !GetAtt Infrastructure.Outputs.TableauServerTargetGroupArn
  TsmTargetGroupArn:
    Description: TSM UI ALB TG
    Value: !GetAtt Infrastructure.Outputs.TsmTargetGroupArn
